config/routes.rb
Rails.application.routes.draw do
  # get 'skills/home'
  # get 'steps/home'
  resources :projects
  root to: "pages#home"
  devise_for :users

  resources :attachments

  get '/feed/user/informations', to:"feeds#informations"
  get '/feed/that_i_can_see', to: "feeds#submission_that_i_can_see"
  get '/project/need', to: "projects#project_needs"
  get '*path', to: "pages#home"
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  has_one_attached :image
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :user
  has_one :project_attachment
  has_one :attachment, through: :project_attachment

  has_many :step_projects
  has_many :steps, through: :step_projects

  has_many :tag_projects
  has_many :tags, through: :tag_projects

  has_many :project_types
  has_many :types, through: :project_types

  def step_projects
    self.steps
  end

  def tag_projects
    Occupation.where(moment: "creators")
  end

  def project_types
    self.types
  end

  def users_informations
    User.find self.user_id
  end
end

app/models/project_type.rb
class ProjectType < ApplicationRecord
  belongs_to :project
  belongs_to :type
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/step.rb
class Step < ApplicationRecord
end

app/models/step_project.rb
class StepProject < ApplicationRecord
  belongs_to :step
  belongs_to :project
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  has_many_attached :files
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tag_project.rb
class TagProject < ApplicationRecord
  belongs_to :tag
  belongs_to :project
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :submissions
  
  has_many :projects

  has_many :user_occupations
  has_many :occupations, through: :user_occupations

  has_many :user_skills
  has_many :skills, through: :user_skills

  has_many :user_goals
  has_many :goals, through: :user_goals

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def projects
    submissions = self.submissions
    submissions
  end


  def self.map_reponse

    byebug 
    # if self.occupations[0]['moment'] != "creators" 
    #   return
    # end
    # resp = {
    #   "user" => self,
    #   "occupation" => self.occupation
    # }
  end
end

app/models/user_goal.rb
class UserGoal < ApplicationRecord
  belongs_to :goal
  belongs_to :user
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  def project_needs
    makers = User.where.not(id: current_user.id)
    render json: { "steps": Step.all, "tags": Occupation.where(moment: "creators"), "types": Type.all , makers: makers}
  end
  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    Project.create(title: params[:title], description: params[:description], user_id:current_user.id)
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project, {})
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>